# Generated by Django 5.0.1 on 2024-01-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('solicitante', models.CharField(max_length=256)),
                ('tempo', models.DateTimeField()),
                ('lugar', models.CharField(max_length=16)),
                ('descricao', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=16)),
            ],
        ),
    ]
