# Generated by Django 5.0.1 on 2024-01-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM PROGESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluido')], default='', max_length=16),
        ),
    ]
