# Generated by Django 5.0.1 on 2024-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM PROGRESSO', 'Em Progresso'), ('CONCLUIDO', 'Concluido')], default='', max_length=16),
        ),
    ]
